/*
 * Created on 2006-08-06
 *
 * @author M.Olszewski 
 */

package net.java.dante.sim.data.object;

import net.java.dante.sim.data.template.types.WeaponTemplateData;

/**
 * Base class representing weapon system.
 *
 * @author M.Olszewski 
 */
public abstract class WeaponSystem
{
  /** Name of weapon's type. */
  private String type;
  /** Weapon's template data for this weapon system. */
  WeaponTemplateData templateData;

  
  /**
   * Constructor of {@link WeaponSystem} class.
   * 
   * @param weaponType - name of weapon's type.
   * @param weaponTemplateData - weapon's template data.
   */
  protected WeaponSystem(String weaponType, 
      WeaponTemplateData weaponTemplateData)
  {
    if (weaponType == null)
    {
      throw new NullPointerException("Specified weaponType is null!");
    }
    if (weaponTemplateData == null)
    {
      throw new NullPointerException("Specified weaponTemplateData is null!");
    }
    if (weaponType.length() <= 0)
    {
      throw new IllegalArgumentException("Invalid argument weaponType: type of weapon cannot be an empty string!");
    }
    
    type = weaponType;
    templateData = weaponTemplateData;
  }

  /**
   * Gets name of this weapon's type.
   * 
   * @return Returns name of this weapon's type.
   */
  public String getType()
  {
    return type;
  }

  /**
   * Gets range of this {@link ServerWeaponSystem}.
   * 
   * @return Returns range of this {@link ServerWeaponSystem}.
   */
  public double getRange()
  {
    return templateData.getRange();
  }

  /**
   * Gets speed of projectiles generated by this {@link ServerWeaponSystem}.
   * 
   * @return Returns speed of projectiles generated by this {@link ServerWeaponSystem}.
   */
  public double getMaxSpeed()
  {
    return templateData.getMaxSpeed();
  }
  
  /**
   * Gets weapon's explosion range.
   * 
   * @return Returns weapon's explosion range.
   */
  public double getExplosionRange()
  {
    return templateData.getExplosionRange();
  }

  /**
   * Gets minimum damage that can be done by projectiles generated by 
   * this {@link ServerWeaponSystem}.
   * 
   * @return Returns minimum damage that can be done by projectiles generated by 
   *         this {@link ServerWeaponSystem}.
   */
  public int getMinDamage()
  {
    return templateData.getMinDamage();
  }

  /**
   * Gets maximum damage that can be done by projectiles generated by 
   * this {@link ServerWeaponSystem}.
   * 
   * @return Returns maximum damage that can be done by projectiles generated by 
   *         this {@link ServerWeaponSystem}.
   */
  public int getMaxDamage()
  {
    return templateData.getMaxDamage();
  }

  /**
   * Gets reload time of this {@link ServerWeaponSystem}.
   * 
   * @return Returns reload time of this {@link ServerWeaponSystem}.
   */
  public long getReloadTime()
  {
    return templateData.getReloadTime();
  }

  /**
   * Gets the projectile's size.
   *
   * @return Returns the projectile's size.
   */
  public ObjectSize getProjectileSize()
  {
    return templateData.getProjectileSize();
  }
  
  /** 
   * @see java.lang.Object#toString()
   */
  @Override
  public String toString()
  {
    return (getClass() + "[type=" + type + "; templateData=" + templateData + "]");
  }
}