/*
 * Created on 2006-08-22
 *
 * @author M.Olszewski
 */

package net.java.dante.gui.common.messages.receiver;


import net.java.dante.gui.common.games.GameOutputData;
import net.java.dante.receiver.ReceiverMessage;
import net.java.dante.sim.io.OutputData;

/**
 * Class wrapping {@link net.java.dante.sim.io.OutputData} object
 * ({@link net.java.dante.sim.Simulation} output) created by game
 * with specified identifier.
 *
 * @author M.Olszewski
 */
public class SimulationOutputMessage implements ReceiverMessage, GameOutputData
{
  /** Game's identifier for which output data was generated. */
  private Integer gameId;
  /** Output data generated by simulation denoted by the specified identifier. */
  private OutputData data;


  /**
   * Creates instance of {@link SimulationOutputMessage} class with the specified
   * parameters.
   *
   * @param gameIdentifier - game's identifier for which output data was generated.
   * @param outputData - output data generated by simulation denoted the by specified identifier.
   */
  public SimulationOutputMessage(Integer gameIdentifier, OutputData outputData)
  {
    if (gameIdentifier == null)
    {
      throw new NullPointerException("Specified gameIdentifier is null!");
    }
    if (outputData == null)
    {
      throw new NullPointerException("Specified outputData is null!");
    }

    gameId = gameIdentifier;
    data   = outputData;
  }


  /**
   * @see net.java.dante.gui.common.games.GameOutputData#getGameId()
   */
  public Integer getGameId()
  {
    return gameId;
  }

  /**
   * Gets output data wrapped by this message.
   *
   * @return Returns output data wrapped by this message.
   */
  public OutputData getOutputData()
  {
    return data;
  }

  /**
   * @see java.lang.Object#hashCode()
   */
  @Override
  public int hashCode()
  {
    final int PRIME = 37;
    int result = 17;

    result = PRIME * result + data.hashCode();
    result = PRIME * result + gameId.hashCode();

    return result;
  }

  /**
   * @see java.lang.Object#equals(java.lang.Object)
   */
  @Override
  public boolean equals(Object object)
  {
    boolean equal = (this == object);
    if (!equal && (object instanceof SimulationOutputMessage))
    {
      final SimulationOutputMessage other = (SimulationOutputMessage) object;
      equal = ((gameId.equals(other.gameId)) &&
               (data.equals(other.data)));
    }
    return equal;
  }

  /**
   * @see java.lang.Object#toString()
   */
  @Override
  public String toString()
  {
    return (getClass() + "[gameId=" + gameId + "; data=" + data + "]");
  }
}