/*
 * Created on 2006-07-12
 *
 * @author M.Olszewski 
 */

package net.java.dante.sim.data.template.types;


/**
 * Names of all fixed attributes of weapon system objects.
 * 
 * @author M.Olszewski
 */
public final class WeaponAttributesNames
{
  /** Attribute indicating weapon's type. */
  public static final String WEAPON_TYPE = "TYPE";
  /** Attribute indicating weapon's range. */
  public static final String RANGE = "RANGE";
  /** Attribute indicating maximum speed of projectiles generated by weapon's system. */
  public static final String MAX_SPEED = "MAX_SPEED";
  /** Attribute indicating weapon's explosion range. */
  public static final String EXPLOSION_RANGE = "EXPLOSION_RANGE";
  /** Attribute indicating weapon's minimum damage. */
  public static final String MIN_DAMAGE = "MIN_DAMAGE";
  /** Attribute indicating weapon's maximum damage. */
  public static final String MAX_DAMAGE = "MAX_DAMAGE";
  /** Attribute indicating weapon's reload time in milliseconds. */
  public static final String RELOAD_TIME = "RELOAD_TIME";
  /** Attribute indicating projectile's size. */
  public static final String PROJECTILE_SIZE = "PROJECTILE_SIZE";
  

  /**
   * Private constructor - no external class creation, no inheritance.
   */
  private WeaponAttributesNames()
  {
    // Intentionally left empty.
  }
}