/*
 * Created on 2006-07-04
 *
 * @author M.Olszewski 
 */

package net.java.dante.sim.io;

/**
 * Common interface for classes representing output data generated by
 * {@link net.java.dante.sim.Simulation}.
 *
 * @author M.Olszewski
 */
public interface OutputData
{
  // Intentionally left empty.
}