/*
 * Created on 2006-07-04
 *
 * @author M.Olszewski 
 */

package net.java.dante.sim.io;

/**
 * Common interface for classes that are notified when data generated 
 * by {@link net.java.dante.sim.Simulation} (implementations of {@link OutputData} interface)
 * is ready to be read and processed.
 *
 * @author M.Olszewski
 */
public interface SimulationOutput
{
  /**
   * Method invoked when data generated by {@link net.java.dante.sim.Simulation} is ready
   * to be read and processed.
   * 
   * @param data - implementation of {@link OutputData} interface, representing
   *        output data of {@link net.java.dante.sim.Simulation}. 
   */
  public void dataReady(OutputData data);
}