/*
 * Created on 2006-08-31
 *
 * @author M.Olszewski
 */

package net.java.dante.algorithms.data;

import net.java.dante.sim.data.object.ObjectSize;

/**
 * Interface defining data of weapon system used by some agent.
 *
 * @author M.Olszewski
 */
public interface WeaponData
{
  /**
   * Gets range of this weapon.
   *
   * @return Returns range of this weapon.
   */
  double getRange();

  /**
   * Gets speed of projectiles generated by this weapon.
   *
   * @return Returns speed of projectiles generated by this weapon.
   */
  double getMaxSpeed();

  /**
   * Gets weapon's explosion range.
   *
   * @return Returns weapon's explosion range.
   */
  double getExplosionRange();

  /**
   * Gets minimum damage that can be done by projectiles generated by
   * this weapon.
   *
   * @return Returns minimum damage that can be done by projectiles generated by
   *         this weapon.
   */
  int getMinDamage();

  /**
   * Gets maximum damage that can be done by projectiles generated by
   * this weapon.
   *
   * @return Returns maximum damage that can be done by projectiles generated by
   *         this weapon.
   */
  int getMaxDamage();

  /**
   * Gets reload time of this weapon.
   *
   * @return Returns reload time of this weapon.
   */
  long getReloadTime();

  /**
   * Gets the projectile's size.
   *
   * @return Returns the projectile's size.
   */
  ObjectSize getProjectileSize();
}